Task2 almost finished.

diff --git a/task0/script b/task0/script
--- a/task0/script
+++ b/task0/script
@@ -12,7 +12,7 @@ fi
 if [ ! -w $log ]
 then
  echo "ERROR: cant open $log for writing"
- exit
+ exit 1
 fi
 #
 
@@ -24,16 +24,18 @@ dd if=/dev/random bs=1K count=$random_size >> $log
 #logroate file
 if [ ! -e $config ]
 then
- $(./script_init)
+ echo  "ERROR: $config file do not exist. Use script_init file to create it."
+ echo  "Usage: './script_init like cron'   or"
+ echo  "       './script_init like daemon'"
 fi
 
 sudo logrotate $config
 #
 
 #debug
-ls -la /var/log/time*
+#ls -la /var/log/time*
 #
 
-
+exit 0
 
 
diff --git a/task0/script_init b/task0/script_init
--- a/task0/script_init
+++ b/task0/script_init
@@ -4,19 +4,38 @@ config="/var/log/timebomb.conf"
 log="/var/log/timebomb.log"
 script="$(pwd)/script"
 
+#check if input param exists
+
+if [ "$1" != "like" ]
+then
+ echo  "ERROR: cant init without param."
+ echo  "Usage: './script_init like cron'   or"
+ echo  "       './script_init like daemon'"
+ exit 1
+elif [ "$2" != "cron" -a "$2" != "daemon" ]
+then
+ echo  "ERROR: wrong like param is $2"
+ echo  "Usage: './script_init like cron'   or"
+ echo  "       './script_init like daemon'"
+ exit 1
+else
+ echo "STATUS: script initialised like $2"
+fi
+#
+
 #check create logrotate configuration file
-if [ ! -e $config ] 
-then 
+if [ ! -e $config ]
+then
  touch $config
 fi
 
 if [ ! -w $config ]
 then
- chmod +rw $config 
+ chmod +rw $config
 fi
 
 if [ ! -w $config -o ! -r $config ]
-then 
+then
  echo "ERROR: cant create readable/writable config file at $config"
  exit
 fi
@@ -32,39 +51,44 @@ printf "$log {\n"\
 
 echo "STATUS: $config was created sucessfully"
 
-#add line to crontab if its not exist
-new_line="* * * * * $script"
-IFS=$'\n'
+#if option equal `like cron` then add line to crontab and restart service
+if [ "$2" = "cron" ]
+then
+ #add line to crontab if its not exist
+ new_line="* * * * * $script"
+ IFS=$'\n'
 
-line_exists=false
-for line in $(crontab -l)
-do
- if [ $line = $new_line ]
+ line_exists=false
+ for line in $(crontab -l)
+ do
+  if [ $line = $new_line ]
+  then
+   line_exists=true
+   echo "STATUS: New line already exists in crontab."
+   break
+  fi
+ done
+
+ if [ $line_exists = "false" ]
  then
-  line_exists=true
-  echo "STATUS: New line already exists in crontab."
-  break
+  (crontab -l; echo "$new_line") | crontab -
+  echo "STATUS: New line added to crontab."
  fi
-done
+ #
 
-if [ $line_exists = "false" ]
-then
- (crontab -l; echo "$new_line") | crontab -
- echo "STATUS: New line added to crontab."
-fi
-#
+ #start or restart cron service to apply new crontab
+ cron_pid=$(pidof cron)
+ if [ ${#cron_pid} = 0 ]
+ then
+  sudo service cron start &>/dev/null
+  echo "STATUS: Cron service started."
+ else
+  sudo service cron restart &>/dev/null
+  echo "STATUS: Cron service restarted."
+ fi
+ #
 
-#start or restart cron service to apply new crontab
-cron_pid=$(pidof cron)
-if [ ${#cron_pid} = 0 ]
-then
- sudo service cron start &>/dev/null
- echo "STATUS: Cron service started."
-else
- sudo service cron restart &>/dev/null
- echo "STATUS: Cron service restarted."
-fi
-#
+fi #end of 'like cron' option
 
 echo "STATUS: Init finished sucessfully. Use 'ls -lah /var/log/time*' to check the result."
 
